### ISSUE TITLE
Feature Request: Internationalisation

### ISSUE THREAD

**Issue by saschafoerster** [AddReminders/Reminders-in-RocketChat#4]
Is there a way to help to translate the Reminders-app? :)

**Comment by murtaza98** [comment]
Internationalisation is the next feature that I'm working on within this app. I'm currently preparing the code structure to support multiple languages. Plus, those translation JSON files will be public so you should be able to contribute to them and enhance them for everyone. I'll keep you posted about this here :smile:

**Comment by ankar84** [comment]
> those translation JSON files will be public so you should be able to contribute to them and enhance them for everyone

Nice! I'd love to!

**Comment by murtaza98** [comment]
Hello @saschafoerster @ankar84 I'm happy to share that this feature has been introduced in the latest version of this app (i.e. `2.1.0` ). In this new version, 2 new languages were added ( Portuguese :brazil: and German :de: ) and new languages will soon follow - it will be much quicker now since the app is now equipped to deal with multiple languages. Hence, it's just a matter of working on pure translation files. 

Please check out the complete guide on setting up preferred language [here](https://add-reminders.gitbook.io/docs/guides/other-guides/change-preferred-language). 

Do note that right now due to a Rocket.Chat's app engine limitation, the user has to set their language manually. The app engine doesn't share the user's preferred language with any apps. However, I'll talk to the apps-engine team about this and see if we can modify the app's engine to allow sharing of users' preferred language with apps. If that change is added there, then I'll update the app accordingly to use the user's preferred language, that way they don't have to set it up manually. I will keep you posted about any updates on that :smile:

**Comment by saschafoerster** [comment]
@murtaza98 I would like to improve translations. But still, source files are not visible here on Github. There are plenty of incorrect and misleading translations. But it's a good start! :) Keep up the pace!

**Comment by murtaza98** [comment]
Hi @saschafoerster I completely understand that and I was in fact expecting some issues with translations since neither Portuguese nor German is my native language & so I had to fully rely on machine translations. That being said, if you wish to share any suggestions to improve the translations, then please check out this [translation repo](https://github.com/AddReminders/App-Translations) which contains all the translations for this app. Truly appreciate any help there :smile:

**Comment by saschafoerster** [comment]
@murtaza98 There you go: https://github.com/AddReminders/App-Translations/pull/3
